# -*- coding: utf-8 -*-
"""ML Project Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D159nRvbfmWThRLJCsT0087zke50g4s3

1️⃣ Final Project Structure
"""

breast_cancer_ml_project
│
├── src
│   ├── __init__.py
│   ├── logger.py
│   ├── exception.py
│   ├── utils.py
│
│   ├── components
│   │   ├── __init__.py
│   │   ├── data_ingestion.py
│   │   ├── data_transformation.py
│   │   ├── model_trainer.py
│
│   ├── pipeline
│   │   ├── __init__.py
│   │   ├── train_pipeline.py
│   │   ├── predict_pipeline.py
│
├── notebook
│   └── EDA.ipynb
│
├── import_data.py
├── app.py
├── setup.py
├── requirements.txt
├── README.md
├── LICENSE
└── .gitignore